# Generated by Django 4.1.13 on 2024-11-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('R', 'Read'), ('CR', 'Currently Reading'), ('WR', 'Want to Read')], default='WR', max_length=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
