# Generated by Django 4.1.13 on 2024-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.CharField(blank=True, help_text="E.g., '50% completed' or 'Chapter 5 of 20'", max_length=100, null=True),
        ),
    ]
